services:
  postgresql:
    image: postgres:16
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: project_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    restart: unless-stopped
    networks:
      - project_network
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./backend/db/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      DSN: postgresql://user:pass@postgresql:5432/project_db?sslmode=disable
      PORT: 8080
      JWT_SECRET: f7afdb469d75f215b99de2d9c7c228a3e6b4ba928651c9c68a5c7b2f8c0fb827
      FRONTEND_URL: http://localhost:3000
    restart: always
    networks:
      - project_network
    depends_on:
      - postgresql

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_BASE_URL: http://localhost:8080
    restart: always
    networks:
      - project_network

networks:
  project_network:
    driver: bridge

volumes:
  postgresql_data:
