apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.global.postgresql.name }}-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/{{ .Values.global.postgresql.name }}"
    type: DirectoryOrCreate