apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.postgresql.name }}-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi