apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.postgresql.name }}
  labels:
    run: {{ .Values.global.postgresql.name }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: {{ .Values.global.postgresql.name }}